### ISSUE TITLE
Suggestions to improve

### ISSUE THREAD

**Issue by Maclenn77** [fabianofrank/todo-app#3]
Hi, Fabiano:

My connection was bad and I was unable to follow  the solution, but what I could understand, I give you some suggestions:

You don't need to display again all the elements each time are updated, you only need to update the DOM Elements. For example, when you're adding a new task, you're creating a new element that shows the description of the task (a div). Also, it's useful that you add some tags inside those elements to identify them and manipulate them later.

For example, for a new tag, you have these metadata:` { index: 1, description: 'new task', completed; false }`. That's in the local storage, but you also want that the info is shown in the DOM Element. I did the following thing:

As I used an `ul`, each time that I create the task, I create a `li` element. For index, I gave an ID to li, for complete, I mark in the input checked if it's true, for remove and edit I use the id of the parent element (in this case, `li`). So, each time that I create a new task, it creates a new DOM element that shows in this way

`<li id='1'> <input type='checkbox' > <span> new task </span> <I>these are the icon</i></li>`

You can check in the [live version](https://maclenn77.github.io/To-Do-List/).

When removed, I request to remove the parent element by ID. If an element is removed, the ID of elements with an upper index is updated. For example, if the removed element has an index = 2, instead of displaying everything again, I request to change the id of the `li` of all the upper elements.

I think that you could have problems with the _clear all_ function if you display again each time that you remove an element, when you can simply update the elements. 

I found these readings useful for understanding how to manipulate DOM elements with event listeners, maybe they also work for you: 
 
- https://www.cookieshq.co.uk/posts/event-listeners-not-working-troublelshooting
- https://typeofnan.dev/how-to-bind-event-listeners-on-dynamically-created-elements-in-javascript/

**Comment by fabianofrank** [comment]
Thank you for the amazing suggestions, that was really thoughtful.
